# Generated by Django 4.0.3 on 2022-03-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minhajapp', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default='images/default.jpg', upload_to='images'),
        ),
    ]
