# Generated by Django 4.0.3 on 2022-03-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minhajapp', '0004_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=1000),
        ),
    ]
