# Generated by Django 4.0.3 on 2022-03-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minhajapp', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='slug',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
