# Generated by Django 4.0.3 on 2022-03-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minhajapp', '0008_packages_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
